source 'https://rubygems.org'
group :jekyll_plugins do
    gem 'base64'
    gem 'bigdecimal'
    gem 'bibtex-ruby', '~> 6.2'
    gem 'classifier-reborn'
    gem 'csv'
    gem 'jekyll'
    gem 'jekyll-archives'
    gem 'jekyll-feed'
    gem 'jekyll-get-json'
    gem 'jekyll-imagemagick'
    gem 'jekyll-link-attributes'
    gem 'jekyll-minifier'
    gem 'jekyll-paginate-v2'
    gem 'jekyll-scholar'
    gem 'jekyll-sitemap'
    gem 'jekyll-toc'
    gem 'logger'
    gem 'mini_racer'
    gem 'observer'
    gem 'ostruct'
    gem 'unicode_utils'
    gem 'webrick'
end
group :other_plugins do
    gem 'feedjira'
    gem 'httparty'
end
